// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entities.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Event {

  /// <summary>Holder for reflection information generated from entities.proto</summary>
  public static partial class EntitiesReflection {

    #region Descriptor
    /// <summary>File descriptor for entities.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntitiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lbnRpdGllcy5wcm90bxIFZXZlbnQibAoGU3RhdHVzEhEKCWRldmljZV9J",
            "RBgBIAEoCRITCgtkZXZpY2VfbmFtZRgCIAEoCRIOCgZzdGF0dXMYAyABKAgS",
            "FQoNb2NjdXJyZWRfdGltZRgEIAEoBBITCgtkZXNjcmlwdGlvbhgFIAEoCSKx",
            "CgoFQWxhcm0SKgoKYWxhcm1fdHlwZRgBIAEoDjIWLmV2ZW50LkFsYXJtLkFs",
            "YXJtVHlwZRIRCglkZXZpY2VfSUQYAiABKAkSEwoLZGV2aWNlX25hbWUYAyAB",
            "KAkSEgoKc3RhcnRfdGltZRgEIAEoBBIQCghlbmRfdGltZRgFIAEoBBIOCgZk",
            "ZXRhaWwYBiABKAkinQkKCUFsYXJtVHlwZRIMCghOb3RFdmVudBAAEhMKD0Rl",
            "dmljZUhlYXJ0YmVhdBABEh0KGURldmljZVRyaWdnZXJEaWdpdGFsSW5wdXQQ",
            "AhIdChlEZXZpY2VUcmlnZ2VyRGlnaXRhbFJlbGF5EAMSGgoWVmlkZW9Tb3Vy",
            "Y2VNb3Rpb25BbGFybRAEEhkKFVZpZGVvU291cmNlU2lnbmFsTG9zcxAFEhYK",
            "ElZpZGVvU291cmNlU2hhZGluZxAGEi0KKVZpZGVvU291cmNlSW1hZ2VUb29C",
            "cmlnaHRBbmFseXRpY3NTZXJ2aWNlEAcSKwonVmlkZW9Tb3VyY2VJbWFnZVRv",
            "b0JyaWdodEltYWdpbmdTZXJ2aWNlEAgSLQopVmlkZW9Tb3VyY2VJbWFnZVRv",
            "b0JyaWdodFJlY29yZGluZ1NlcnZpY2UQCRIhCh1SdWxlRW5naW5lTGluZURl",
            "dGVjdG9yQ3Jvc3NlZBAKEigKJFJ1bGVFbmdpbmVGaWVsZERldGVjdG9yT2Jq",
            "ZWN0c0luc2lkZRALEikKJVJ1bGVFbmdpbmVGaWVsZERldGVjdG9yT2JqZWN0",
            "c091dHNpZGUQDBIxCi1SdWxlRW5naW5lRmllbGREZXRlY3Rvck9iamVjdHNJ",
            "bnNpZGVPck91dHNpZGUQDRIrCidSdWxlRW5naW5lRmllbGREZXRlY3Rvck9i",
            "amVjdHNMb2l0ZXJpbmcQDhIhCh1SdWxlRW5naW5lT2JqZWN0RGV0ZWN0b3JU",
            "b2tlbhAPEiEKHVJ1bGVFbmdpbmVPYmplY3REZXRlY3RvckxlYXZlEBASLwor",
            "UnVsZUVuZ2luZU9iamVjdERldGVjdG9yT2JqZWN0c1Rva2VuT3JMZWF2ZRAR",
            "EiUKIVJ1bGVFbmdpbmVDb3VudEFnZ3JlZ2F0aW9uQ291bnRlchASEhoKFlJ1",
            "bGVFbmdpbmVGaXJlRGV0ZWN0b3IQExIbChdSdWxlRW5naW5lUGxhdGVEZXRl",
            "Y3RvchAUEiYKIlJ1bGVFbmdpbmVGYWNlQW5hbHlzaXNGYWNlRGV0ZWN0b3IQ",
            "FRImCiJSdWxlRW5naW5lQ2VsbE1vdGlvbkRldGVjdG9yTW90aW9uEBYSJgoi",
            "TW9uaXRvcmluZ1Byb2ZpbGVBY3RpdmVDb25uZWN0aW9ucxAZEhQKEEV2ZW50",
            "TW90aW9uQWxhcm0QGhINCglWaWRlb01hc2sQGxINCglWaWRlb0xvc3MQHBIQ",
            "CgxDcm9zc2luZ0xpbmUQHRIVChFQZXJpbWV0ZXJEZWZlbmRlchAeEhIKDkF1",
            "ZGlvRGV0ZWN0aW9uEB8SEgoOSW50cnVzaW9uVHJhY2UQIBIRCg1TRENhcmRG",
            "YWlsdXJlECESEgoOU0RDYXJkT3ZlcmZsb3cQIhIOCgpTRENhcmRGdWxsECMS",
            "DgoKQWxhcm1JbnB1dBAkEg8KC0FsYXJtT3V0cHV0ECUSDgoKUmVjb3JkTG9z",
            "dBAmEhEKDVJlc291cmNlVXNhZ2UQJxITCg9SZWNvcmRFeGNlcHRpb24QKBIZ",
            "ChVWb2x1bUNhcGFjaXR5SXNUb29Mb3cQKSLHAQoFRXZlbnQSKgoKZXZlbnRf",
            "dHlwZRgBIAEoDjIWLmV2ZW50LkV2ZW50LkV2ZW50VHlwZRIRCglkZXZpY2Vf",
            "SUQYAiABKAkSEwoLZGV2aWNlX25hbWUYAyABKAkSFQoNb2NjdXJyZWRfdGlt",
            "ZRgEIAEoBBIOCgZkZXRhaWwYBiABKAkiQwoJRXZlbnRUeXBlEhcKE01lZGlh",
            "UHJvZmlsZUNoYW5nZWQQABIdChlNZWRpYUNvbmZpZ3VyYXRpb25DaGFuZ2Vk",
            "EAEiLQoKQWxhcm1DbGVhchIRCglkZXZpY2VfaWQYASABKAkSDAoEdGltZRgC",
            "IAEoAyo6CgpFdmVudFRvcGljEhQKEERldmljZUV2ZW50VG9waWMQABIWChJP",
            "cmlnaW5hbEV2ZW50VG9waWMQASo9CgtTdGF0dXNUb3BpYxIVChFEZXZpY2VT",
            "dGF0dXNUb3BpYxAAEhcKE09yaWdpbmFsU3RhdHVzVG9waWMQAipVCgpBbGFy",
            "bVRvcGljEhQKEERldmljZUFsYXJtVG9waWMQABIZChVEZXZpY2VBbGFybUNs",
            "ZWFyVG9waWMQAxIWChJPcmlnaW5hbEFsYXJtVG9waWMQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Event.EventTopic), typeof(global::Event.StatusTopic), typeof(global::Event.AlarmTopic), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Event.Status), global::Event.Status.Parser, new[]{ "DeviceID", "DeviceName", "Status_", "OccurredTime", "Description" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Event.Alarm), global::Event.Alarm.Parser, new[]{ "AlarmType", "DeviceID", "DeviceName", "StartTime", "EndTime", "Detail" }, null, new[]{ typeof(global::Event.Alarm.Types.AlarmType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Event.Event), global::Event.Event.Parser, new[]{ "EventType", "DeviceID", "DeviceName", "OccurredTime", "Detail" }, null, new[]{ typeof(global::Event.Event.Types.EventType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Event.AlarmClear), global::Event.AlarmClear.Parser, new[]{ "DeviceId", "Time" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EventTopic {
    [pbr::OriginalName("DeviceEventTopic")] DeviceEventTopic = 0,
    [pbr::OriginalName("OriginalEventTopic")] OriginalEventTopic = 1,
  }

  public enum StatusTopic {
    [pbr::OriginalName("DeviceStatusTopic")] DeviceStatusTopic = 0,
    /// <summary>
    ///ONVIFIPCStatusTopic = 1;
    ///NVR7128StatusTopic = 2;
    /// </summary>
    [pbr::OriginalName("OriginalStatusTopic")] OriginalStatusTopic = 2,
  }

  public enum AlarmTopic {
    [pbr::OriginalName("DeviceAlarmTopic")] DeviceAlarmTopic = 0,
    /// <summary>
    ///ONVIFIPCAlarmTopic = 1;
    ///NVR7128AlarmTopic = 2;
    /// </summary>
    [pbr::OriginalName("DeviceAlarmClearTopic")] DeviceAlarmClearTopic = 3,
    [pbr::OriginalName("OriginalAlarmTopic")] OriginalAlarmTopic = 4,
  }

  #endregion

  #region Messages
  public sealed partial class Status : pb::IMessage<Status> {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Event.EntitiesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status(Status other) : this() {
      deviceID_ = other.deviceID_;
      deviceName_ = other.deviceName_;
      status_ = other.status_;
      occurredTime_ = other.occurredTime_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "device_ID" field.</summary>
    public const int DeviceIDFieldNumber = 1;
    private string deviceID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceID {
      get { return deviceID_; }
      set {
        deviceID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_name" field.</summary>
    public const int DeviceNameFieldNumber = 2;
    private string deviceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceName {
      get { return deviceName_; }
      set {
        deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int Status_FieldNumber = 3;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Status_ {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "occurred_time" field.</summary>
    public const int OccurredTimeFieldNumber = 4;
    private ulong occurredTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong OccurredTime {
      get { return occurredTime_; }
      set {
        occurredTime_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 5;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeviceID != other.DeviceID) return false;
      if (DeviceName != other.DeviceName) return false;
      if (Status_ != other.Status_) return false;
      if (OccurredTime != other.OccurredTime) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DeviceID.Length != 0) hash ^= DeviceID.GetHashCode();
      if (DeviceName.Length != 0) hash ^= DeviceName.GetHashCode();
      if (Status_ != false) hash ^= Status_.GetHashCode();
      if (OccurredTime != 0UL) hash ^= OccurredTime.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DeviceID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DeviceID);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceName);
      }
      if (Status_ != false) {
        output.WriteRawTag(24);
        output.WriteBool(Status_);
      }
      if (OccurredTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(OccurredTime);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DeviceID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceID);
      }
      if (DeviceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
      }
      if (Status_ != false) {
        size += 1 + 1;
      }
      if (OccurredTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(OccurredTime);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.DeviceID.Length != 0) {
        DeviceID = other.DeviceID;
      }
      if (other.DeviceName.Length != 0) {
        DeviceName = other.DeviceName;
      }
      if (other.Status_ != false) {
        Status_ = other.Status_;
      }
      if (other.OccurredTime != 0UL) {
        OccurredTime = other.OccurredTime;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DeviceID = input.ReadString();
            break;
          }
          case 18: {
            DeviceName = input.ReadString();
            break;
          }
          case 24: {
            Status_ = input.ReadBool();
            break;
          }
          case 32: {
            OccurredTime = input.ReadUInt64();
            break;
          }
          case 42: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Alarm : pb::IMessage<Alarm> {
    private static readonly pb::MessageParser<Alarm> _parser = new pb::MessageParser<Alarm>(() => new Alarm());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Alarm> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Event.EntitiesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Alarm() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Alarm(Alarm other) : this() {
      alarmType_ = other.alarmType_;
      deviceID_ = other.deviceID_;
      deviceName_ = other.deviceName_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      detail_ = other.detail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Alarm Clone() {
      return new Alarm(this);
    }

    /// <summary>Field number for the "alarm_type" field.</summary>
    public const int AlarmTypeFieldNumber = 1;
    private global::Event.Alarm.Types.AlarmType alarmType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event.Alarm.Types.AlarmType AlarmType {
      get { return alarmType_; }
      set {
        alarmType_ = value;
      }
    }

    /// <summary>Field number for the "device_ID" field.</summary>
    public const int DeviceIDFieldNumber = 2;
    private string deviceID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceID {
      get { return deviceID_; }
      set {
        deviceID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_name" field.</summary>
    public const int DeviceNameFieldNumber = 3;
    private string deviceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceName {
      get { return deviceName_; }
      set {
        deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 4;
    private ulong startTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 5;
    private ulong endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "detail" field.</summary>
    public const int DetailFieldNumber = 6;
    private string detail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Detail {
      get { return detail_; }
      set {
        detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Alarm);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Alarm other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AlarmType != other.AlarmType) return false;
      if (DeviceID != other.DeviceID) return false;
      if (DeviceName != other.DeviceName) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (Detail != other.Detail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AlarmType != 0) hash ^= AlarmType.GetHashCode();
      if (DeviceID.Length != 0) hash ^= DeviceID.GetHashCode();
      if (DeviceName.Length != 0) hash ^= DeviceName.GetHashCode();
      if (StartTime != 0UL) hash ^= StartTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (Detail.Length != 0) hash ^= Detail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AlarmType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AlarmType);
      }
      if (DeviceID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceID);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DeviceName);
      }
      if (StartTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(EndTime);
      }
      if (Detail.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Detail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AlarmType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AlarmType);
      }
      if (DeviceID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceID);
      }
      if (DeviceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
      }
      if (StartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (Detail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Alarm other) {
      if (other == null) {
        return;
      }
      if (other.AlarmType != 0) {
        AlarmType = other.AlarmType;
      }
      if (other.DeviceID.Length != 0) {
        DeviceID = other.DeviceID;
      }
      if (other.DeviceName.Length != 0) {
        DeviceName = other.DeviceName;
      }
      if (other.StartTime != 0UL) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.Detail.Length != 0) {
        Detail = other.Detail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            alarmType_ = (global::Event.Alarm.Types.AlarmType) input.ReadEnum();
            break;
          }
          case 18: {
            DeviceID = input.ReadString();
            break;
          }
          case 26: {
            DeviceName = input.ReadString();
            break;
          }
          case 32: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 40: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 50: {
            Detail = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Alarm message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum AlarmType {
        [pbr::OriginalName("NotEvent")] NotEvent = 0,
        [pbr::OriginalName("DeviceHeartbeat")] DeviceHeartbeat = 1,
        [pbr::OriginalName("DeviceTriggerDigitalInput")] DeviceTriggerDigitalInput = 2,
        [pbr::OriginalName("DeviceTriggerDigitalRelay")] DeviceTriggerDigitalRelay = 3,
        [pbr::OriginalName("VideoSourceMotionAlarm")] VideoSourceMotionAlarm = 4,
        [pbr::OriginalName("VideoSourceSignalLoss")] VideoSourceSignalLoss = 5,
        [pbr::OriginalName("VideoSourceShading")] VideoSourceShading = 6,
        [pbr::OriginalName("VideoSourceImageTooBrightAnalyticsService")] VideoSourceImageTooBrightAnalyticsService = 7,
        [pbr::OriginalName("VideoSourceImageTooBrightImagingService")] VideoSourceImageTooBrightImagingService = 8,
        [pbr::OriginalName("VideoSourceImageTooBrightRecordingService")] VideoSourceImageTooBrightRecordingService = 9,
        [pbr::OriginalName("RuleEngineLineDetectorCrossed")] RuleEngineLineDetectorCrossed = 10,
        [pbr::OriginalName("RuleEngineFieldDetectorObjectsInside")] RuleEngineFieldDetectorObjectsInside = 11,
        [pbr::OriginalName("RuleEngineFieldDetectorObjectsOutside")] RuleEngineFieldDetectorObjectsOutside = 12,
        [pbr::OriginalName("RuleEngineFieldDetectorObjectsInsideOrOutside")] RuleEngineFieldDetectorObjectsInsideOrOutside = 13,
        [pbr::OriginalName("RuleEngineFieldDetectorObjectsLoitering")] RuleEngineFieldDetectorObjectsLoitering = 14,
        [pbr::OriginalName("RuleEngineObjectDetectorToken")] RuleEngineObjectDetectorToken = 15,
        [pbr::OriginalName("RuleEngineObjectDetectorLeave")] RuleEngineObjectDetectorLeave = 16,
        [pbr::OriginalName("RuleEngineObjectDetectorObjectsTokenOrLeave")] RuleEngineObjectDetectorObjectsTokenOrLeave = 17,
        [pbr::OriginalName("RuleEngineCountAggregationCounter")] RuleEngineCountAggregationCounter = 18,
        [pbr::OriginalName("RuleEngineFireDetector")] RuleEngineFireDetector = 19,
        [pbr::OriginalName("RuleEnginePlateDetector")] RuleEnginePlateDetector = 20,
        [pbr::OriginalName("RuleEngineFaceAnalysisFaceDetector")] RuleEngineFaceAnalysisFaceDetector = 21,
        [pbr::OriginalName("RuleEngineCellMotionDetectorMotion")] RuleEngineCellMotionDetectorMotion = 22,
        [pbr::OriginalName("MonitoringProfileActiveConnections")] MonitoringProfileActiveConnections = 25,
        [pbr::OriginalName("EventMotionAlarm")] EventMotionAlarm = 26,
        [pbr::OriginalName("VideoMask")] VideoMask = 27,
        [pbr::OriginalName("VideoLoss")] VideoLoss = 28,
        [pbr::OriginalName("CrossingLine")] CrossingLine = 29,
        [pbr::OriginalName("PerimeterDefender")] PerimeterDefender = 30,
        [pbr::OriginalName("AudioDetection")] AudioDetection = 31,
        [pbr::OriginalName("IntrusionTrace")] IntrusionTrace = 32,
        [pbr::OriginalName("SDCardFailure")] SdcardFailure = 33,
        [pbr::OriginalName("SDCardOverflow")] SdcardOverflow = 34,
        [pbr::OriginalName("SDCardFull")] SdcardFull = 35,
        [pbr::OriginalName("AlarmInput")] AlarmInput = 36,
        [pbr::OriginalName("AlarmOutput")] AlarmOutput = 37,
        /// <summary>
        ///录像丢失
        /// </summary>
        [pbr::OriginalName("RecordLost")] RecordLost = 38,
        /// <summary>
        ///资源使用率告警
        /// </summary>
        [pbr::OriginalName("ResourceUsage")] ResourceUsage = 39,
        /// <summary>
        ///录像异常
        /// </summary>
        [pbr::OriginalName("RecordException")] RecordException = 40,
        /// <summary>
        ///ipsan卷容量过低
        /// </summary>
        [pbr::OriginalName("VolumCapacityIsTooLow")] VolumCapacityIsTooLow = 41,
      }

    }
    #endregion

  }

  public sealed partial class Event : pb::IMessage<Event> {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Event.EntitiesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event(Event other) : this() {
      eventType_ = other.eventType_;
      deviceID_ = other.deviceID_;
      deviceName_ = other.deviceName_;
      occurredTime_ = other.occurredTime_;
      detail_ = other.detail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::Event.Event.Types.EventType eventType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Event.Event.Types.EventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "device_ID" field.</summary>
    public const int DeviceIDFieldNumber = 2;
    private string deviceID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceID {
      get { return deviceID_; }
      set {
        deviceID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_name" field.</summary>
    public const int DeviceNameFieldNumber = 3;
    private string deviceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceName {
      get { return deviceName_; }
      set {
        deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "occurred_time" field.</summary>
    public const int OccurredTimeFieldNumber = 4;
    private ulong occurredTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong OccurredTime {
      get { return occurredTime_; }
      set {
        occurredTime_ = value;
      }
    }

    /// <summary>Field number for the "detail" field.</summary>
    public const int DetailFieldNumber = 6;
    private string detail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Detail {
      get { return detail_; }
      set {
        detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (DeviceID != other.DeviceID) return false;
      if (DeviceName != other.DeviceName) return false;
      if (OccurredTime != other.OccurredTime) return false;
      if (Detail != other.Detail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != 0) hash ^= EventType.GetHashCode();
      if (DeviceID.Length != 0) hash ^= DeviceID.GetHashCode();
      if (DeviceName.Length != 0) hash ^= DeviceName.GetHashCode();
      if (OccurredTime != 0UL) hash ^= OccurredTime.GetHashCode();
      if (Detail.Length != 0) hash ^= Detail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EventType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (DeviceID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceID);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DeviceName);
      }
      if (OccurredTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(OccurredTime);
      }
      if (Detail.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Detail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EventType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (DeviceID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceID);
      }
      if (DeviceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
      }
      if (OccurredTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(OccurredTime);
      }
      if (Detail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.EventType != 0) {
        EventType = other.EventType;
      }
      if (other.DeviceID.Length != 0) {
        DeviceID = other.DeviceID;
      }
      if (other.DeviceName.Length != 0) {
        DeviceName = other.DeviceName;
      }
      if (other.OccurredTime != 0UL) {
        OccurredTime = other.OccurredTime;
      }
      if (other.Detail.Length != 0) {
        Detail = other.Detail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            eventType_ = (global::Event.Event.Types.EventType) input.ReadEnum();
            break;
          }
          case 18: {
            DeviceID = input.ReadString();
            break;
          }
          case 26: {
            DeviceName = input.ReadString();
            break;
          }
          case 32: {
            OccurredTime = input.ReadUInt64();
            break;
          }
          case 50: {
            Detail = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Event message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum EventType {
        [pbr::OriginalName("MediaProfileChanged")] MediaProfileChanged = 0,
        [pbr::OriginalName("MediaConfigurationChanged")] MediaConfigurationChanged = 1,
      }

    }
    #endregion

  }

  public sealed partial class AlarmClear : pb::IMessage<AlarmClear> {
    private static readonly pb::MessageParser<AlarmClear> _parser = new pb::MessageParser<AlarmClear>(() => new AlarmClear());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AlarmClear> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Event.EntitiesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AlarmClear() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AlarmClear(AlarmClear other) : this() {
      deviceId_ = other.deviceId_;
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AlarmClear Clone() {
      return new AlarmClear(this);
    }

    /// <summary>Field number for the "device_id" field.</summary>
    public const int DeviceIdFieldNumber = 1;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 2;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AlarmClear);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AlarmClear other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeviceId != other.DeviceId) return false;
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DeviceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DeviceId);
      }
      if (Time != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AlarmClear other) {
      if (other == null) {
        return;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DeviceId = input.ReadString();
            break;
          }
          case 16: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
