// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: system_config.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SystemConfig {
  /// <summary>
  ///service and action definition
  /// </summary>
  public static partial class Manage
  {
    static readonly string __ServiceName = "systemConfig.Manage";

    static readonly grpc::Marshaller<global::SystemConfig.SaveReserveDurationRequest> __Marshaller_SaveReserveDurationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.SaveReserveDurationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.SaveReserveDurationResponse> __Marshaller_SaveReserveDurationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.SaveReserveDurationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.QueryConfigRequest> __Marshaller_QueryConfigRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.QueryConfigRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.QueryReserveConfigResponse> __Marshaller_QueryReserveConfigResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.QueryReserveConfigResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.QueryConfigResponse> __Marshaller_QueryConfigResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.QueryConfigResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.QueryRequest> __Marshaller_QueryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.QueryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.QueryResponse> __Marshaller_QueryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.QueryResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.ImportLanguageResourceRequest> __Marshaller_ImportLanguageResourceRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.ImportLanguageResourceRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.ImportLanguageResourceResponse> __Marshaller_ImportLanguageResourceResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.ImportLanguageResourceResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.SetIntegratedPlatformConfigRequest> __Marshaller_SetIntegratedPlatformConfigRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.SetIntegratedPlatformConfigRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.SetIntegratedPlatformConfigResponse> __Marshaller_SetIntegratedPlatformConfigResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.SetIntegratedPlatformConfigResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.GetIntegratedPlatformConfigRequest> __Marshaller_GetIntegratedPlatformConfigRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.GetIntegratedPlatformConfigRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SystemConfig.GetIntegratedPlatformConfigResponse> __Marshaller_GetIntegratedPlatformConfigResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SystemConfig.GetIntegratedPlatformConfigResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::SystemConfig.SaveReserveDurationRequest, global::SystemConfig.SaveReserveDurationResponse> __Method_SaveReserveDuration = new grpc::Method<global::SystemConfig.SaveReserveDurationRequest, global::SystemConfig.SaveReserveDurationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveReserveDuration",
        __Marshaller_SaveReserveDurationRequest,
        __Marshaller_SaveReserveDurationResponse);

    static readonly grpc::Method<global::SystemConfig.QueryConfigRequest, global::SystemConfig.QueryReserveConfigResponse> __Method_QueryReserveConfig = new grpc::Method<global::SystemConfig.QueryConfigRequest, global::SystemConfig.QueryReserveConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryReserveConfig",
        __Marshaller_QueryConfigRequest,
        __Marshaller_QueryReserveConfigResponse);

    static readonly grpc::Method<global::SystemConfig.QueryConfigRequest, global::SystemConfig.QueryConfigResponse> __Method_QueryAvaliableLanguages = new grpc::Method<global::SystemConfig.QueryConfigRequest, global::SystemConfig.QueryConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryAvaliableLanguages",
        __Marshaller_QueryConfigRequest,
        __Marshaller_QueryConfigResponse);

    static readonly grpc::Method<global::SystemConfig.QueryRequest, global::SystemConfig.QueryResponse> __Method_QueryResources = new grpc::Method<global::SystemConfig.QueryRequest, global::SystemConfig.QueryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryResources",
        __Marshaller_QueryRequest,
        __Marshaller_QueryResponse);

    static readonly grpc::Method<global::SystemConfig.QueryRequest, global::SystemConfig.QueryResponse> __Method_QueryProductionData = new grpc::Method<global::SystemConfig.QueryRequest, global::SystemConfig.QueryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "QueryProductionData",
        __Marshaller_QueryRequest,
        __Marshaller_QueryResponse);

    static readonly grpc::Method<global::SystemConfig.ImportLanguageResourceRequest, global::SystemConfig.ImportLanguageResourceResponse> __Method_ImportLanguageResource = new grpc::Method<global::SystemConfig.ImportLanguageResourceRequest, global::SystemConfig.ImportLanguageResourceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ImportLanguageResource",
        __Marshaller_ImportLanguageResourceRequest,
        __Marshaller_ImportLanguageResourceResponse);

    static readonly grpc::Method<global::SystemConfig.SetIntegratedPlatformConfigRequest, global::SystemConfig.SetIntegratedPlatformConfigResponse> __Method_SetIntegratedPlatformConfig = new grpc::Method<global::SystemConfig.SetIntegratedPlatformConfigRequest, global::SystemConfig.SetIntegratedPlatformConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetIntegratedPlatformConfig",
        __Marshaller_SetIntegratedPlatformConfigRequest,
        __Marshaller_SetIntegratedPlatformConfigResponse);

    static readonly grpc::Method<global::SystemConfig.GetIntegratedPlatformConfigRequest, global::SystemConfig.GetIntegratedPlatformConfigResponse> __Method_GetIntegratedPlatformConfig = new grpc::Method<global::SystemConfig.GetIntegratedPlatformConfigRequest, global::SystemConfig.GetIntegratedPlatformConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetIntegratedPlatformConfig",
        __Marshaller_GetIntegratedPlatformConfigRequest,
        __Marshaller_GetIntegratedPlatformConfigResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SystemConfig.SystemConfigReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Manage</summary>
    public abstract partial class ManageBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.SaveReserveDurationResponse> SaveReserveDuration(global::SystemConfig.SaveReserveDurationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.QueryReserveConfigResponse> QueryReserveConfig(global::SystemConfig.QueryConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.QueryConfigResponse> QueryAvaliableLanguages(global::SystemConfig.QueryConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.QueryResponse> QueryResources(global::SystemConfig.QueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.QueryResponse> QueryProductionData(global::SystemConfig.QueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.ImportLanguageResourceResponse> ImportLanguageResource(global::SystemConfig.ImportLanguageResourceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.SetIntegratedPlatformConfigResponse> SetIntegratedPlatformConfig(global::SystemConfig.SetIntegratedPlatformConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SystemConfig.GetIntegratedPlatformConfigResponse> GetIntegratedPlatformConfig(global::SystemConfig.GetIntegratedPlatformConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Manage</summary>
    public partial class ManageClient : grpc::ClientBase<ManageClient>
    {
      /// <summary>Creates a new client for Manage</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ManageClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Manage that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ManageClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ManageClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ManageClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SystemConfig.SaveReserveDurationResponse SaveReserveDuration(global::SystemConfig.SaveReserveDurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveReserveDuration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.SaveReserveDurationResponse SaveReserveDuration(global::SystemConfig.SaveReserveDurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveReserveDuration, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.SaveReserveDurationResponse> SaveReserveDurationAsync(global::SystemConfig.SaveReserveDurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveReserveDurationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.SaveReserveDurationResponse> SaveReserveDurationAsync(global::SystemConfig.SaveReserveDurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveReserveDuration, null, options, request);
      }
      public virtual global::SystemConfig.QueryReserveConfigResponse QueryReserveConfig(global::SystemConfig.QueryConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryReserveConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.QueryReserveConfigResponse QueryReserveConfig(global::SystemConfig.QueryConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryReserveConfig, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryReserveConfigResponse> QueryReserveConfigAsync(global::SystemConfig.QueryConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryReserveConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryReserveConfigResponse> QueryReserveConfigAsync(global::SystemConfig.QueryConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryReserveConfig, null, options, request);
      }
      public virtual global::SystemConfig.QueryConfigResponse QueryAvaliableLanguages(global::SystemConfig.QueryConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAvaliableLanguages(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.QueryConfigResponse QueryAvaliableLanguages(global::SystemConfig.QueryConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryAvaliableLanguages, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryConfigResponse> QueryAvaliableLanguagesAsync(global::SystemConfig.QueryConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAvaliableLanguagesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryConfigResponse> QueryAvaliableLanguagesAsync(global::SystemConfig.QueryConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryAvaliableLanguages, null, options, request);
      }
      public virtual global::SystemConfig.QueryResponse QueryResources(global::SystemConfig.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryResources(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.QueryResponse QueryResources(global::SystemConfig.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryResources, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryResponse> QueryResourcesAsync(global::SystemConfig.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryResourcesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryResponse> QueryResourcesAsync(global::SystemConfig.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryResources, null, options, request);
      }
      public virtual global::SystemConfig.QueryResponse QueryProductionData(global::SystemConfig.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryProductionData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.QueryResponse QueryProductionData(global::SystemConfig.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_QueryProductionData, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryResponse> QueryProductionDataAsync(global::SystemConfig.QueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryProductionDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.QueryResponse> QueryProductionDataAsync(global::SystemConfig.QueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_QueryProductionData, null, options, request);
      }
      public virtual global::SystemConfig.ImportLanguageResourceResponse ImportLanguageResource(global::SystemConfig.ImportLanguageResourceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImportLanguageResource(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.ImportLanguageResourceResponse ImportLanguageResource(global::SystemConfig.ImportLanguageResourceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImportLanguageResource, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.ImportLanguageResourceResponse> ImportLanguageResourceAsync(global::SystemConfig.ImportLanguageResourceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ImportLanguageResourceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.ImportLanguageResourceResponse> ImportLanguageResourceAsync(global::SystemConfig.ImportLanguageResourceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImportLanguageResource, null, options, request);
      }
      public virtual global::SystemConfig.SetIntegratedPlatformConfigResponse SetIntegratedPlatformConfig(global::SystemConfig.SetIntegratedPlatformConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetIntegratedPlatformConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.SetIntegratedPlatformConfigResponse SetIntegratedPlatformConfig(global::SystemConfig.SetIntegratedPlatformConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetIntegratedPlatformConfig, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.SetIntegratedPlatformConfigResponse> SetIntegratedPlatformConfigAsync(global::SystemConfig.SetIntegratedPlatformConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetIntegratedPlatformConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.SetIntegratedPlatformConfigResponse> SetIntegratedPlatformConfigAsync(global::SystemConfig.SetIntegratedPlatformConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetIntegratedPlatformConfig, null, options, request);
      }
      public virtual global::SystemConfig.GetIntegratedPlatformConfigResponse GetIntegratedPlatformConfig(global::SystemConfig.GetIntegratedPlatformConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetIntegratedPlatformConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SystemConfig.GetIntegratedPlatformConfigResponse GetIntegratedPlatformConfig(global::SystemConfig.GetIntegratedPlatformConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetIntegratedPlatformConfig, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.GetIntegratedPlatformConfigResponse> GetIntegratedPlatformConfigAsync(global::SystemConfig.GetIntegratedPlatformConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetIntegratedPlatformConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SystemConfig.GetIntegratedPlatformConfigResponse> GetIntegratedPlatformConfigAsync(global::SystemConfig.GetIntegratedPlatformConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetIntegratedPlatformConfig, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ManageClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ManageClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ManageBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SaveReserveDuration, serviceImpl.SaveReserveDuration)
          .AddMethod(__Method_QueryReserveConfig, serviceImpl.QueryReserveConfig)
          .AddMethod(__Method_QueryAvaliableLanguages, serviceImpl.QueryAvaliableLanguages)
          .AddMethod(__Method_QueryResources, serviceImpl.QueryResources)
          .AddMethod(__Method_QueryProductionData, serviceImpl.QueryProductionData)
          .AddMethod(__Method_ImportLanguageResource, serviceImpl.ImportLanguageResource)
          .AddMethod(__Method_SetIntegratedPlatformConfig, serviceImpl.SetIntegratedPlatformConfig)
          .AddMethod(__Method_GetIntegratedPlatformConfig, serviceImpl.GetIntegratedPlatformConfig).Build();
    }

  }
}
#endregion
