// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: video_on_demand.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcVideoOnDemand {
  public static partial class VideoOnDemand
  {
    static readonly string __ServiceName = "GrpcVideoOnDemand.VideoOnDemand";

    static readonly grpc::Marshaller<global::GrpcVideoOnDemand.RecordFileQueryRequest> __Marshaller_RecordFileQueryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcVideoOnDemand.RecordFileQueryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcVideoOnDemand.RecordFileQueryReply> __Marshaller_RecordFileQueryReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcVideoOnDemand.RecordFileQueryReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcVideoOnDemand.RecordFileQueryRequest, global::GrpcVideoOnDemand.RecordFileQueryReply> __Method_RecordFileQuery = new grpc::Method<global::GrpcVideoOnDemand.RecordFileQueryRequest, global::GrpcVideoOnDemand.RecordFileQueryReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RecordFileQuery",
        __Marshaller_RecordFileQueryRequest,
        __Marshaller_RecordFileQueryReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcVideoOnDemand.VideoOnDemandReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VideoOnDemand</summary>
    public abstract partial class VideoOnDemandBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcVideoOnDemand.RecordFileQueryReply> RecordFileQuery(global::GrpcVideoOnDemand.RecordFileQueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VideoOnDemand</summary>
    public partial class VideoOnDemandClient : grpc::ClientBase<VideoOnDemandClient>
    {
      /// <summary>Creates a new client for VideoOnDemand</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VideoOnDemandClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VideoOnDemand that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VideoOnDemandClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VideoOnDemandClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VideoOnDemandClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcVideoOnDemand.RecordFileQueryReply RecordFileQuery(global::GrpcVideoOnDemand.RecordFileQueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecordFileQuery(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcVideoOnDemand.RecordFileQueryReply RecordFileQuery(global::GrpcVideoOnDemand.RecordFileQueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RecordFileQuery, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcVideoOnDemand.RecordFileQueryReply> RecordFileQueryAsync(global::GrpcVideoOnDemand.RecordFileQueryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecordFileQueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcVideoOnDemand.RecordFileQueryReply> RecordFileQueryAsync(global::GrpcVideoOnDemand.RecordFileQueryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RecordFileQuery, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override VideoOnDemandClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new VideoOnDemandClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(VideoOnDemandBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RecordFileQuery, serviceImpl.RecordFileQuery).Build();
    }

  }
}
#endregion
