// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptz_control.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace GrpcPtzControl {
  public static partial class PtzControl
  {
    static readonly string __ServiceName = "GrpcPtzControl.PtzControl";

    static readonly grpc::Marshaller<global::GrpcPtzControl.PtzDirectRequest> __Marshaller_PtzDirectRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcPtzControl.PtzDirectRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcPtzControl.PtzDirectReply> __Marshaller_PtzDirectReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcPtzControl.PtzDirectReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcPtzControl.PtzDirectRequest, global::GrpcPtzControl.PtzDirectReply> __Method_PtzDirect = new grpc::Method<global::GrpcPtzControl.PtzDirectRequest, global::GrpcPtzControl.PtzDirectReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PtzDirect",
        __Marshaller_PtzDirectRequest,
        __Marshaller_PtzDirectReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcPtzControl.PtzControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PtzControl</summary>
    public abstract partial class PtzControlBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcPtzControl.PtzDirectReply> PtzDirect(global::GrpcPtzControl.PtzDirectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PtzControl</summary>
    public partial class PtzControlClient : grpc::ClientBase<PtzControlClient>
    {
      /// <summary>Creates a new client for PtzControl</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PtzControlClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PtzControl that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PtzControlClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PtzControlClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PtzControlClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcPtzControl.PtzDirectReply PtzDirect(global::GrpcPtzControl.PtzDirectRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PtzDirect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcPtzControl.PtzDirectReply PtzDirect(global::GrpcPtzControl.PtzDirectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PtzDirect, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcPtzControl.PtzDirectReply> PtzDirectAsync(global::GrpcPtzControl.PtzDirectRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PtzDirectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcPtzControl.PtzDirectReply> PtzDirectAsync(global::GrpcPtzControl.PtzDirectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PtzDirect, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PtzControlClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PtzControlClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PtzControlBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PtzDirect, serviceImpl.PtzDirect).Build();
    }

  }
}
#endregion
