// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptz_control.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcPtzControl {

  /// <summary>Holder for reflection information generated from ptz_control.proto</summary>
  public static partial class PtzControlReflection {

    #region Descriptor
    /// <summary>File descriptor for ptz_control.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PtzControlReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwdHpfY29udHJvbC5wcm90bxIOR3JwY1B0ekNvbnRyb2wiYwoQUHR6RGly",
            "ZWN0UmVxdWVzdBIsCgh1Y29tbWFuZBgBIAEoDjIaLkdycGNQdHpDb250cm9s",
            "LlBUWkNvbW1hbmQSDwoHZHdTcGVlZBgCIAEoBRIQCghkZXZpY2VpZBgDIAEo",
            "CSIhCg5QdHpEaXJlY3RSZXBseRIPCgdtZXNzYWdlGAEgASgJKucBCgpQVFpD",
            "b21tYW5kEggKBFN0b3AQABIGCgJVcBABEgoKBlVwTGVmdBACEgsKB1VwUmln",
            "aHQQAxIICgREb3duEAQSDAoIRG93bkxlZnQQBRINCglEb3duUmlnaHQQBhII",
            "CgRMZWZ0EAcSCQoFUmlnaHQQCBIKCgZGb2N1czEQCRIKCgZGb2N1czIQChIJ",
            "CgVab29tMRALEgkKBVpvb20yEAwSCQoFSXJpczEQDRIJCgVJcmlzMhAOEg0K",
            "CVNldFByZXNldBAPEg0KCUdldFByZXNldBAQEhAKDFJlbW92ZVByZXNldBAR",
            "Ml0KClB0ekNvbnRyb2wSTwoJUHR6RGlyZWN0EiAuR3JwY1B0ekNvbnRyb2wu",
            "UHR6RGlyZWN0UmVxdWVzdBoeLkdycGNQdHpDb250cm9sLlB0ekRpcmVjdFJl",
            "cGx5IgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GrpcPtzControl.PTZCommand), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcPtzControl.PtzDirectRequest), global::GrpcPtzControl.PtzDirectRequest.Parser, new[]{ "Ucommand", "DwSpeed", "Deviceid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GrpcPtzControl.PtzDirectReply), global::GrpcPtzControl.PtzDirectReply.Parser, new[]{ "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PTZCommand {
    [pbr::OriginalName("Stop")] Stop = 0,
    [pbr::OriginalName("Up")] Up = 1,
    [pbr::OriginalName("UpLeft")] UpLeft = 2,
    [pbr::OriginalName("UpRight")] UpRight = 3,
    [pbr::OriginalName("Down")] Down = 4,
    [pbr::OriginalName("DownLeft")] DownLeft = 5,
    [pbr::OriginalName("DownRight")] DownRight = 6,
    [pbr::OriginalName("Left")] Left = 7,
    [pbr::OriginalName("Right")] Right = 8,
    [pbr::OriginalName("Focus1")] Focus1 = 9,
    [pbr::OriginalName("Focus2")] Focus2 = 10,
    [pbr::OriginalName("Zoom1")] Zoom1 = 11,
    [pbr::OriginalName("Zoom2")] Zoom2 = 12,
    [pbr::OriginalName("Iris1")] Iris1 = 13,
    [pbr::OriginalName("Iris2")] Iris2 = 14,
    [pbr::OriginalName("SetPreset")] SetPreset = 15,
    [pbr::OriginalName("GetPreset")] GetPreset = 16,
    [pbr::OriginalName("RemovePreset")] RemovePreset = 17,
  }

  #endregion

  #region Messages
  /// <summary>
  /// The request message.
  /// </summary>
  public sealed partial class PtzDirectRequest : pb::IMessage<PtzDirectRequest> {
    private static readonly pb::MessageParser<PtzDirectRequest> _parser = new pb::MessageParser<PtzDirectRequest>(() => new PtzDirectRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PtzDirectRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcPtzControl.PtzControlReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectRequest(PtzDirectRequest other) : this() {
      ucommand_ = other.ucommand_;
      dwSpeed_ = other.dwSpeed_;
      deviceid_ = other.deviceid_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectRequest Clone() {
      return new PtzDirectRequest(this);
    }

    /// <summary>Field number for the "ucommand" field.</summary>
    public const int UcommandFieldNumber = 1;
    private global::GrpcPtzControl.PTZCommand ucommand_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GrpcPtzControl.PTZCommand Ucommand {
      get { return ucommand_; }
      set {
        ucommand_ = value;
      }
    }

    /// <summary>Field number for the "dwSpeed" field.</summary>
    public const int DwSpeedFieldNumber = 2;
    private int dwSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DwSpeed {
      get { return dwSpeed_; }
      set {
        dwSpeed_ = value;
      }
    }

    /// <summary>Field number for the "deviceid" field.</summary>
    public const int DeviceidFieldNumber = 3;
    private string deviceid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Deviceid {
      get { return deviceid_; }
      set {
        deviceid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PtzDirectRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PtzDirectRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ucommand != other.Ucommand) return false;
      if (DwSpeed != other.DwSpeed) return false;
      if (Deviceid != other.Deviceid) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Ucommand != 0) hash ^= Ucommand.GetHashCode();
      if (DwSpeed != 0) hash ^= DwSpeed.GetHashCode();
      if (Deviceid.Length != 0) hash ^= Deviceid.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Ucommand != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Ucommand);
      }
      if (DwSpeed != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DwSpeed);
      }
      if (Deviceid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Deviceid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Ucommand != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Ucommand);
      }
      if (DwSpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DwSpeed);
      }
      if (Deviceid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Deviceid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PtzDirectRequest other) {
      if (other == null) {
        return;
      }
      if (other.Ucommand != 0) {
        Ucommand = other.Ucommand;
      }
      if (other.DwSpeed != 0) {
        DwSpeed = other.DwSpeed;
      }
      if (other.Deviceid.Length != 0) {
        Deviceid = other.Deviceid;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ucommand_ = (global::GrpcPtzControl.PTZCommand) input.ReadEnum();
            break;
          }
          case 16: {
            DwSpeed = input.ReadInt32();
            break;
          }
          case 26: {
            Deviceid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The response message.
  /// </summary>
  public sealed partial class PtzDirectReply : pb::IMessage<PtzDirectReply> {
    private static readonly pb::MessageParser<PtzDirectReply> _parser = new pb::MessageParser<PtzDirectReply>(() => new PtzDirectReply());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PtzDirectReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GrpcPtzControl.PtzControlReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectReply(PtzDirectReply other) : this() {
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PtzDirectReply Clone() {
      return new PtzDirectReply(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PtzDirectReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PtzDirectReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PtzDirectReply other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
